# Generated by Django 2.1.2 on 2018-12-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Untitled', max_length=128)),
                ('coordinate_x', models.FloatField(blank=True)),
                ('coordinate_y', models.FloatField(blank=True)),
            ],
        ),
    ]
